// const eventsInYear = t.type({// if you need this
//   address: t.string,
//   city: t.string,
//   country: t.string,
//   district: t.unknown,
//   division_keys: t.array(t.string),
//   end_date: t.string,
//   event_code: t.string,
//   event_type: t.number,
//   event_type_string: t.string,
//   first_event_code: t.string,
//   first_event_id: t.unknown,
//   gmaps_place_id: t.string,
//   gmaps_url: t.string,
//   key: t.string,
//   lat: t.number,
//   lng: t.number,
//   location_name: t.string,
//   name: t.string,
//   parent_event_key: t.unknown,
//   playoff_type: t.number,
//   playoff_type_string: t.string,
//   postal_code: t.string,
//   remap_teams: t.unknown,
//   short_name: t.string,
//   start_date: t.string,
//   state_prov: t.string,
//   timezone: t.string,
//   webcasts: t.array(
//     t.type({
//       channel: t.string,
//       type: t.string,
//     })
//   ),
//   website: t.string,
//   week: t.number,
//   year: t.number,
// });